name: myapp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  sign_in_button: ^3.2.0
  sign_button: ^2.0.6
  passwordfield: ^0.2.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  logger: ^2.3.0
  cloud_firestore: ^4.17.4
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/